dependencies:
  java_agent_lib: /ssd_home/yangheechan/LLMFL/PingFL/MethodCallGraphBuilder/target/MethodCallGraphBuilder-1.0.jar
  bug_exec: /home/yangheechan/.d4j_src/defects4j-2.0.1/framework/bin/defects4j
